### PR TITLE
Springboot@3.0

### PR DESCRIPTION
**Pull request by yeongsheng-tan**
Upgrade to springboot@3.0.x

### CODE REVIEW

**Comment by terryyin** [comment]
Looks like you’ve found a dead class CustomRestExceptionHandler.

**Comment by yeongsheng-tan** [comment]
@terryyin I'm still unable to solve issue with the @OrderBy annotation for in Note entity class for `descendantsInBreathFirstOrder` property:
```
      Suppressed: org.hibernate.metamodel.mapping.ordering.ast.PathResolutionException: Could not resolve order-by path : com.odde.doughnut.entities.Note.descendantsInBreathFirstOrder -> notes_closure
                at org.hibernate.metamodel.mapping.ordering.ast.RootSequencePart.resolvePathPart(RootSequencePart.java:57) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.ast.PathConsumer.consumeIdentifier(PathConsumer.java:66) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.ast.ParseTreeVisitor.visitDotIdentifier(ParseTreeVisitor.java:139) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.ast.ParseTreeVisitor.visitDotIdentifierExpression(ParseTreeVisitor.java:129) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.ast.ParseTreeVisitor.visitDotIdentifierExpression(ParseTreeVisitor.java:29) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.grammars.ordering.OrderingParser$DotIdentifierExpressionContext.accept(OrderingParser.java:322) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.ast.ParseTreeVisitor.visitSortSpecification(ParseTreeVisitor.java:64) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.ast.ParseTreeVisitor.visitOrderByFragment(ParseTreeVisitor.java:53) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.OrderByFragmentTranslator.translate(OrderByFragmentTranslator.java:60) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.internal.PluralAttributeMappingImpl.finishInitialization(PluralAttributeMappingImpl.java:242) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.internal.MappingModelCreationHelper.lambda$buildPluralAttributeMapping$5(MappingModelCreationHelper.java:749) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.internal.MappingModelCreationProcess$PostInitCallbackEntry.process(MappingModelCreationProcess.java:210) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.internal.MappingModelCreationProcess.executePostInitCallbacks(MappingModelCreationProcess.java:108) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                ... 35 common frames omitted
```

**Comment by yeongsheng-tan** [comment]
With mysql jar upgrade and springboot upgrade to 3.0.2 does not seem to help. I am beginning to suspect the `@orderby` annotation for in `Note` entity class for `descendantsInBreathFirstOrder` property syntax is no longer supported. @terryyin wonder if you might have any new insights?

```
2023-01-20T19:53:52.088+08:00  INFO 96824 --- [  restartedMain] SQL dialect                              : HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
2023-01-20T19:53:53.518+08:00 ERROR 96824 --- [  restartedMain] j.LocalContainerEntityManagerFactoryBean : Failed to initialize JPA EntityManagerFactory: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is java.lang.IllegalStateException: PostInitCallback queue could not be processed...
        - PostInitCallbackEntry - PluralAttributeMapping(com.odde.doughnut.entities.Note.descendantsInBreathFirstOrder)#finishInitialization

2023-01-20T19:53:53.518+08:00  WARN 96824 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is java.lang.IllegalStateException: PostInitCallback queue could not be processed...
        - PostInitCallbackEntry - PluralAttributeMapping(com.odde.doughnut.entities.Note.descendantsInBreathFirstOrder)#finishInitialization

2023-01-20T19:53:53.519+08:00  INFO 96824 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2023-01-20T19:53:53.527+08:00  INFO 96824 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2023-01-20T19:53:53.529+08:00  INFO 96824 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-01-20T19:53:53.546+08:00  INFO 96824 --- [  restartedMain] .s.b.a.l.ConditionEvaluationReportLogger :

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-01-20T19:53:53.568+08:00 ERROR 96824 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is java.lang.IllegalStateException: PostInitCallback queue could not be processed...
        - PostInitCallbackEntry - PluralAttributeMapping(com.odde.doughnut.entities.Note.descendantsInBreathFirstOrder)#finishInitialization

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1130) ~[spring-context-6.0.4.jar:6.0.4]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:905) ~[spring-context-6.0.4.jar:6.0.4]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.4.jar:6.0.4]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.2.jar:3.0.2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.2.jar:3.0.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.2.jar:3.0.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.2.jar:3.0.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.2.jar:3.0.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.2.jar:3.0.2]
.
.
.
Caused by: java.lang.IllegalStateException: PostInitCallback queue could not be processed...
        - PostInitCallbackEntry - PluralAttributeMapping(com.odde.doughnut.entities.Note.descendantsInBreathFirstOrder)#finishInitialization

        at org.hibernate.metamodel.mapping.internal.MappingModelCreationProcess.executePostInitCallbacks(MappingModelCreationProcess.java:146) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
        at org.hibernate.metamodel.mapping.internal.MappingModelCreationProcess.execute(MappingModelCreationProcess.java:90) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
        at org.hibernate.metamodel.mapping.internal.MappingModelCreationProcess.process(MappingModelCreationProcess.java:39) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
        at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.finishInitialization(MappingMetamodelImpl.java:229) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
        at org.hibernate.metamodel.internal.RuntimeMetamodelsImpl.finishInitialization(RuntimeMetamodelsImpl.java:60) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:415) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1425) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:66) ~[spring-orm-6.0.4.jar:6.0.4]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[spring-orm-6.0.4.jar:6.0.4]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[spring-orm-6.0.4.jar:6.0.4]
        ... 25 common frames omitted
        Suppressed: org.hibernate.metamodel.mapping.ordering.ast.PathResolutionException: Could not resolve order-by path : com.odde.doughnut.entities.Note.descendantsInBreathFirstOrder -> notes_closure
                at org.hibernate.metamodel.mapping.ordering.ast.RootSequencePart.resolvePathPart(RootSequencePart.java:57) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.ast.PathConsumer.consumeIdentifier(PathConsumer.java:66) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.ast.ParseTreeVisitor.visitDotIdentifier(ParseTreeVisitor.java:139) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.ast.ParseTreeVisitor.visitDotIdentifierExpression(ParseTreeVisitor.java:129) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.ast.ParseTreeVisitor.visitDotIdentifierExpression(ParseTreeVisitor.java:29) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.grammars.ordering.OrderingParser$DotIdentifierExpressionContext.accept(OrderingParser.java:322) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.ast.ParseTreeVisitor.visitSortSpecification(ParseTreeVisitor.java:64) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.ast.ParseTreeVisitor.visitOrderByFragment(ParseTreeVisitor.java:53) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.ordering.OrderByFragmentTranslator.translate(OrderByFragmentTranslator.java:60) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.internal.PluralAttributeMappingImpl.finishInitialization(PluralAttributeMappingImpl.java:242) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.internal.MappingModelCreationHelper.lambda$buildPluralAttributeMapping$5(MappingModelCreationHelper.java:749) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.internal.MappingModelCreationProcess$PostInitCallbackEntry.process(MappingModelCreationProcess.java:210) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                at org.hibernate.metamodel.mapping.internal.MappingModelCreationProcess.executePostInitCallbacks(MappingModelCreationProcess.java:108) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
                ... 35 common frames omitted
```

**Comment by terryyin** [comment]
There seems to be a lot of changes including e2e test folder names. I wonder where shall I start to repeat this process?

**Comment by yeongsheng-tan** [comment]
> There seems to be a lot of changes including e2e test folder names. I wonder where shall I start to repeat this process?

Perhaps instead to cherry pick just these:

1. https://github.com/nerds-odd-e/doughnut/pull/984/commits/0b3796875375f11afb23a9da7b8b7555b68695d0
2. https://github.com/nerds-odd-e/doughnut/pull/984/commits/3adaa363dc24f570ed8ae0dfed2103255816c109
3. https://github.com/nerds-odd-e/doughnut/pull/984/commits/3c52cdf991fcf43f3ec90dfb917175922ce0147f
4. https://github.com/nerds-odd-e/doughnut/pull/984/commits/955757d7eae55ac5016585eb30d0feba4972d9c2
5. https://github.com/nerds-odd-e/doughnut/pull/984/commits/f52b24817ec8606c2cae78edc54ae9e38427c3cc
6. https://github.com/nerds-odd-e/doughnut/pull/984/commits/d3845fdebca1bed3c950608487edb49b70f1906b
7. https://github.com/nerds-odd-e/doughnut/pull/984/commits/aaab305171253fc97237d9abcb9713b9f3ce960c
8. https://github.com/nerds-odd-e/doughnut/pull/984/commits/05d06ccab83df46094da0d545e80229a95e1f27c
9. https://github.com/nerds-odd-e/doughnut/pull/984/commits/05b447954f338a742e3647f8555821b1f75bbd92
10. https://github.com/nerds-odd-e/doughnut/pull/984/commits/4920316f7c5210cf664f44fe22487d0dd7b28b8c

**Pull request closed without merging**
